// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WhatsApp
{
    internal sealed partial class Vsix
    {
        public const string Id = "WhatsApp.7b5332db-308e-4ab2-9701-494760aa93b8";
        public const string Name = "WhatsApp";
        public const string Description = @"WhatsWeb for Visual Studio is an innovative extension that brings WhatsApp Web directly into the Visual Studio IDE";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Himanshu Kumar Sharma HKS";
        public const string Tags = "";
    }
}
